"""
SIDEKAP Refactor Script
Memisahkan CSS dan JS dari index.html ke Style.css dan Script.js
"""
import re
import shutil
from pathlib import Path

BASE = Path(r"d:\Semester 6\KP\Codingan")
HTML_FILE  = BASE / "index.html"
CSS_FILE   = BASE / "Style.css"
JS_FILE    = BASE / "Script.js"

# ── Backup index.html ──────────────────────────────────────────────
backup = BASE / "backup" / "index_before_refactor.html"
backup.parent.mkdir(exist_ok=True)
shutil.copy2(HTML_FILE, backup)
print(f"[OK] Backup disimpan: {backup}")

# ── Baca index.html ─────────────────────────────────────────────────
html = HTML_FILE.read_text(encoding="utf-8")

# ── 1. Ekstrak CSS (konten di dalam <style>...</style>) ──────────────
css_match = re.search(r"<style>(.*?)</style>", html, re.DOTALL)
if not css_match:
    raise RuntimeError("Blok <style> tidak ditemukan!")
css_content = css_match.group(1).strip()
print(f"[OK] CSS diekstrak: {len(css_content):,} karakter")

# ── 2. Ekstrak JS (konten di dalam <script> terakhir / tanpa src) ───
# Ambil SEMUA <script> tanpa atribut src (yaitu inline scripts)
inline_scripts = re.findall(r"<script(?!\s+src)[^>]*>(.*?)</script>", html, re.DOTALL)
if not inline_scripts:
    raise RuntimeError("Blok <script> inline tidak ditemukan!")
# Gabungkan semua inline script blocks
js_content = "\n\n".join(s.strip() for s in inline_scripts if s.strip())
print(f"[OK] JS diekstrak: {len(js_content):,} karakter")

# ── 3. Tulis Style.css ──────────────────────────────────────────────
css_header = "/* =================================================\n   SIDEKAP — Style.css\n   Generated by refactor script\n   ================================================= */\n\n"
CSS_FILE.write_text(css_header + css_content, encoding="utf-8")
print(f"[OK] Style.css ditulis: {CSS_FILE.stat().st_size:,} bytes")

# ── 4. Tulis Script.js ──────────────────────────────────────────────
js_header = "/* =================================================\n   SIDEKAP — Script.js\n   Generated by refactor script\n   ================================================= */\n\n"
JS_FILE.write_text(js_header + js_content, encoding="utf-8")
print(f"[OK] Script.js ditulis: {JS_FILE.stat().st_size:,} bytes")

# ── 5. Bersihkan index.html ─────────────────────────────────────────
# Hapus blok <style>...</style>
html_clean = re.sub(r"\s*<style>.*?</style>", "", html, flags=re.DOTALL)

# Hapus semua inline <script>...</script> (tanpa src)
html_clean = re.sub(r"\s*<script(?!\s+src)[^>]*>.*?</script>", "", html_clean, flags=re.DOTALL)

# Tambahkan <link> ke Style.css di dalam <head>, setelah Google Fonts link
link_tag = '\n<link rel="stylesheet" href="Style.css">'
html_clean = re.sub(
    r'(rel="stylesheet">\s*\n)',
    r'\1' + link_tag + '\n',
    html_clean, count=1
)

# Tambahkan <script src="Script.js"> sebelum </body>
script_tag = '\n<script src="Script.js"></script>\n'
html_clean = html_clean.replace("</body>", script_tag + "</body>")

# ── 6. Simpan index.html yang sudah bersih ──────────────────────────
HTML_FILE.write_text(html_clean, encoding="utf-8")
print(f"[OK] index.html dibersihkan: {HTML_FILE.stat().st_size:,} bytes")

# ── 7. Verifikasi ────────────────────────────────────────────────────
result = HTML_FILE.read_text(encoding="utf-8")
has_style_block  = "<style>" in result
has_script_block = bool(re.search(r"<script(?!\s+src)[^>]*>", result))
has_css_link     = 'href="Style.css"' in result
has_js_src       = 'src="Script.js"' in result

print("\n── Verifikasi ──────────────────")
print(f"  <style> block tersisa : {'❌ MASIH ADA' if has_style_block else '✅ Sudah dihapus'}")
print(f"  <script> inline tersisa: {'❌ MASIH ADA' if has_script_block else '✅ Sudah dihapus'}")
print(f"  Link ke Style.css      : {'✅ Ada' if has_css_link else '❌ TIDAK ADA'}")
print(f"  Script src Script.js   : {'✅ Ada' if has_js_src else '❌ TIDAK ADA'}")
print("\n[SELESAI] Refactoring berhasil!")
