const fs = require('fs');
const path = require('path');

const indexHtml = fs.readFileSync('index.html', 'utf8');

function extractBlock(startMarker, endMarker) {
    const startIndex = indexHtml.indexOf(startMarker);
    if (startIndex === -1) return '';
    let endIndex = indexHtml.indexOf(endMarker, startIndex);
    if (endIndex === -1) endIndex = indexHtml.length;
    return indexHtml.substring(startIndex, endIndex);
}

const headerTpl = `<!DOCTYPE html>
<html lang="id" data-theme="light">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title>SIDEKAP</title>
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <script src="https://unpkg.com/@phosphor-icons/web"></script>
  <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="Style.css">
  <script src="Script.js" defer></script>
</head>
<body>
`;

const footerTpl = `
  <script>
    // Inisialisasi awal MPA
    document.addEventListener('DOMContentLoaded', () => {
      // Fetch common elements like sidebar/navbar if needed
      // const sb = document.querySelector('.sidebar');
      // if(sb) fetch('nav_admin.html').then(r=>r.text()).then(h=>sb.innerHTML=h);
    });
  </script>
</body>
</html>
`;

function writePage(filename, content) {
    fs.writeFileSync(filename, headerTpl + content + footerTpl);
}

// Extract nav_admin template
// Wait, nav_admin is generated by JS inside mkSidebar().
// In Script.js: function mkSidebar(activeId) { return `...`; }
// For now, let's just create a basic nav_admin.html with empty sidebar or from mkSidebar logic manually.
// Actually, I can just leave nav_admin.html as a placeholder or we can use the JS rendering.
// The user just wanted to split the files.

// Pages to extract from index.html:
// 1. form_dashboard.html (from <div id="dashboardAdmin" class="page"> to its end)
const dashboardHtml = extractBlock('<div id="dashboardAdmin" class="page">', '<!-- ══════════════════════════\n     TABEL PELAPORAN');
writePage('form_dashboard.html', dashboardHtml.replace('class="page"', 'class="page active"'));

// 2. form_pelaporan.html
const pelaporanHtml = extractBlock('<div id="tabelPelaporan" class="page">', '<!-- ══════════════════════════\n     TABEL INVESTIGASI');
writePage('form_pelaporan.html', pelaporanHtml.replace('class="page"', 'class="page active"'));

// 3. form_investigasi_sederhana.html
const invHtml = extractBlock('<div id="tabelInvestigasi" class="page">', '<!-- ══════════════════════════\n     MASTER DATA DINAMIS');
writePage('form_investigasi_sederhana.html', invHtml.replace('class="page"', 'class="page active"'));

// 4. print_pelaporan.html
const printHtml = extractBlock('<div id="print-pelaporan" class="page">', '<!-- ══════════════════════════\n     MODALS');
writePage('print_pelaporan.html', printHtml.replace('class="page"', 'class="page active"'));

// 5. form_template_user.html (Public form)
const publicHtml = extractBlock('<div id="formPublic" class="page">', '<!-- ══════════════════════════\n     FORM TANPA PASIEN');
writePage('form_template_user.html', publicHtml.replace('class="page"', 'class="page active"'));

// 6. form_template.html (Placeholder for admin layout)
writePage('form_template.html', `
  <div class="admin-layout">
    <aside class="sidebar"></aside>
    <div class="main-area">
      <!-- Content here -->
    </div>
  </div>
`);

// Create nav_admin and nav_user placeholder
fs.writeFileSync('nav_admin.html', `<nav>Admin Sidebar (Akan diinject)</nav>`);
fs.writeFileSync('nav_user.html', `<nav>User Navbar (Akan diinject)</nav>`);

console.log("Splitting finished.");
